name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_INSTANCE_KEY }}
          HOSTNAME: ${{ secrets.SSH_HOST }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          echo "$PRIVATE_KEY" > key.pem && chmod 600 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem ${USER_NAME}@${HOSTNAME} '
              # Now we have got the access of EC2 and we will start the deploy .
              cd /home/ubuntu/react-ssr &&
              git checkout master &&
              git fetch origin &&
              git pull origin &&
              sudo pm2 stop 0 &&
              sudo npm run build &&
              sudo pm2 start &&
              '
